### ISSUE TITLE
Product API

### ISSUE THREAD

**Issue by thoho** [on-api/on-api#1]
API to manage products available for SP from CO. (Copied from old google sheets list)

**Comment by joeseos** [comment]
Maybe TMF Product Catalog Management API can give some inspiration. 

[TMF620_Product_Catalog_Management_API_REST_Specification_R19.0.1.pdf](https://github.com/on-api/on-api/files/4199089/TMF620_Product_Catalog_Management_API_REST_Specification_R19.0.1.pdf)

**Comment by JonasEklundh** [comment]
Seeing how the CO displays products so vastly differently in all web sites, it may be hard to handle with just one specification. That said, I think there are areas where the SP would benefit greatly if they could offload updates to an API instead of doing it manually. I.e. if they could manage campaigns and monthly costs via an API instead of manually, it would be a great first step. Now, as a personal reflection, the process of entering the product is a one-time task and the thing that is mostly updated is monthly, commitment and campaigns, so I think any API should start in that end, instead of trying to be all-encompassing for the product information.

I.e. first an endpoint for seeing all services for a specific CO, eventually with local ID for the SP. Then an API for updating a specific field value for that service, monthly, commitment, startfee etc. Then also an API for listing, deleting and adding campaigns connected to the above services for the CO.

For some CO's, the campaign is just "First 3 months free" or "Free Playstation", but for Tjänstekanonen the campiagn can change the monthly price, commitment period, notice period and start fee as well, so the API should be able to take these things into account.

**Comment by teemufrosen** [comment]
Duplicate issue, closing this copy. New issue is https://github.com/on-api/on-api/issues/22
