### ISSUE TITLE
Product & campaign API

### ISSUE THREAD

**Issue by joeseos** [on-api/on-api#22]
Suggestion on how a product & campaign API could look like:

```
{
  "coServiceId": "3456",
  "coService": "B2-100-100",
  "spService": "Internet 100/100 Mbps",
  "spServiceId": "2347",
  "commitment": "12",
  "noticePeriod": "1",
  "startFee": "295",
  "monthlyCost": "399",
  "startSales": "2020-12-03",
  "endSales": "2030-12-03",
  "campaign": [
    {
      "campId": "1234",
      "campDesciption": "299:- i 6 månader och fri start",
      "startSales": "2020-12-1",
      "endSales": "2030-12-1",
      "discounts": [
        {
          "discountId": "1234",
          "duration": "6",
          "discount": "-100"
        },
        {
          "discountId": "1235",
          "duration": "0",
          "discount": "-295"
        }
      ]
    },
    {
      "campId": "1236",
      "campDesciption": "Fri start",
      "startSales": "2020-12-1",
      "endSales": "2030-12-1",
      "discounts": [
        {
          "discountId": "1234",
          "recurring": "0",
          "duration": "0",
          "discount": "-295"
        }
      ]
    }
  ],
  "isPreactivatd": "false"
}
```
I hope it's self-explanatory, if not, please let me know.

**Comment by JonasEklundh** [comment]
In Tjänsteguiden campaigns can be either discount by percentage, by numeric value or a set value. Or it can be an added cost. So their choices are, for example: "monthly price is [50] [percent/kr] [discount/added/fixed price] for [2] months" se attached image
![C5B98EBC-D895-439C-9570-7C0ED7E36AAC](https://user-images.githubusercontent.com/26897718/102603118-ad78ca00-4122-11eb-9f04-e5f889ddd08b.png)

Also, we have a field for added value, i.e. when the end customer selects this campaign, there is an added value (i.e. a Playstation, router, whatever) for the campaign. This means that instead of a discount on the service, it's actually an added cost to the service. 
![F0FE36A6-91EA-498F-8D9C-C94984177197](https://user-images.githubusercontent.com/26897718/102603348-efa20b80-4122-11eb-98e5-a73f5b555f43.png)

SP can also change the start fee, commitment time and notice period time for the service when the campaign is selected. To accomodate this, the campaign field above would look something like this:

```
{
    ...
    "campaign": [
        {
            "campaignId": "1234",
            "campaignHeadline": "2 månader gratis"
            "startDate": "2020-12-01",
            "endDate": "2030-12-01",
            "adjustment": {
                "monthly": "100",
                "monthlyQualifier": "percentage",
                "monthlyAdjustment": "discount",
                "monthlyPeriod": "2",
                "addedValue": "0",
                "startFee": null,
                "commitment": null,
                "noticePeriod": null
            },
            {
                "campaignId": "1235",
                "campaignHeadline": "Playstation på köpet"
                "startDate": "2020-12-01",
                "endDate": "2021-01-01",
                "adjustment": {
                    "monthly": "129",
                    "monthlyQualifier": "kr",
                    "monthlyAdjustment": "addon",
                    "monthlyPeriod": "indefinate",
                    "addedValue": "3500",
                    "startFee": null,
                    "commitment": "24",
                    "noticePeriod": "6"
                }
            }
        }
    ]
}
```

**Comment by joeseos** [comment]
@JonasEklundh - thank's for your comment. Interesting addition with `"monthlyAdjustment": "addon"`. Would you say that this is a common configuration? I thought about adding support for "products/addons", but that would increase the complexity i guess.

**Comment by JonasEklundh** [comment]
> @JonasEklundh - thank's for your comment. Interesting addition with `"monthlyAdjustment": "addon"`. Would you say that this is a common configuration? I thought about adding support for "products/addons", but that would increase the complexity i guess.

The general idea is that a campaign doesn't always lower the price of the product, it can increase it, if you get added value included in the campaign. This is usually used by lengthening the commitment and notice period, but sometimes by altering the price.

You could always just have a "monthly" field that says what the monthly price will be instead of the parameters for the equation. But you'd also need a monthlyPeriod that can be number of months or always.

**Comment by joeseos** [comment]
To my understanding, this is now supported in v.2.5? @teemufrosen and/or @JonasEklundh do you agree?

**Comment by teemufrosen** [comment]
OK from me. Waiting for @JonasEklundh before closing.
