### ISSUE TITLE
Change required parameters

### ISSUE THREAD

**Issue by joeseos** [on-api/on-api#26]
To my understanding, one of the required parameters to do changes on an already ordered service are `subscriptionId`. Why not only use `spSubscriptionId` instead as this should be given to the CO when the service is ordered?

Example on when `subscriptionId` is required:
https://github.com/on-api/on-api/blob/master/2.4.0/spec/orders.md#deactivate-a-service

**Comment by teemufrosen** [comment]
If we start using spSubscriptionId instead of subscriptionId as mandatory field in orders, I think a value should be mandatory for all order operations. Additionally, each party will have to update subscription data to ensure that operations on existing subscriptions are successful. Updating this data could be a knotty process for some, as there are SP's that don't generate unique subscription id's in their systems.

If the logic is to be changed, it will have an effect on data exchange in other endpoints too, including the new endpoint that supports orders from CO to SP. 

Looking forward to hear the opinions from other parties.

**Comment by wigerhall** [comment]
In our case we have a lot of subscriptions where spSubscriptionId is not set on a subscription. Actually most of our subscriptions doesn't have any spreference value set. 
Legacy in BBE is customerID and the system generates a subscriptionid. So I would be hard for us to use I practice as of now as we are lacking the value. 
We also have cases where the spRefrence is the same on two subscriptions as the spReference in BBE is on the subscription.
BBE handles multiple subscriptions on a customer so I could not just sync the value to the spSubscriptionId. 

I agree that spSubscriptionId would be the the most logical one to use when wanting to call and action on a subscription. But at least BBE isn't close to handling that.

**Comment by joeseos** [comment]
I agree and understand the challenges. I'm thinking that this might be interesting for 2.5 or even 3.0. Probably implementation of new versions will lag a bit, so in that regard, I don't see any issues as long as the suggestion is reasonable in theory.

**Comment by DanielMaintrac** [comment]
I think the documentation might be lacking a bit in this area. spSubscriptionId and spSubscriptionReference should only by required for operations on already connected subscriptions where those values are meant to be changed.  That is probably only the operation "MODIFY".
The use of spSubscriptionId as the primary id or object key was discussed earlier and the decision was that the keys should be generated by the provider of the API for all objects.  

It would be possible to add endpoints to do operations on a subscriptions by spSubscriptionId by extending the suggestions in #24. Like this /Subscriptions/spSubref/< spSubscriptionId >/order/
This would not break backwards compatibility.

**Comment by joeseos** [comment]
@DanielMaintrac Interesting. Just so that I understand, the dicision was that subscriptionId (not the spSubscriptionId) should be stored by the SP when ordering one or more services?

**Comment by DanielMaintrac** [comment]
> @DanielMaintrac Interesting. Just so that I understand, the dicision was that subscriptionId (not the spSubscriptionId) should be stored by the SP when ordering one or more services?

I don't remember which field sparked the discussion but the discussion ended that the ID for each object should be generated by the system that hosts the API. So in the case of subscriptionId and spSubscriptionId it is clearly subscriptionId when referencing a subscription for a service hosted by the CO and the API is hosted by the CO. The fields spSubscriptionId and spReference were added primarily to enable verification of billing rows and the possibility for the SP that whishes to have a reference between the transmission subscription sold by the CO and the end customer subscription that the SP sells to the end customer.

I stand by my previous comment that if the need exists we should find a way to enable references through spSubscriptionId if its value have been set.

**Comment by wigerhall** [comment]
So, subscriptionsId is always generated by CO and is unique, spReference is Mandatory and spSubscriptionId is Optional when Order ACTVIATE. 
spReference could be used by TL as both customerRef and subscriptionRef in documentation. This makes it bit more tricky in BBEs logic as I don't want to have just another reference when I already have CustomerID and is primary key in logic. I want to use spReference=>CustiomerID and spSubscriptionId=> subscription.sprefrence. 
I present both values if create on ACTIVATE. 
If only mandatory field spRefrence is set then I do this:
spReference=>CustiomerID
subscription.spRefernce=spSubscriptionId. 

That leaves me with a question about MODIFY. 
MODIFY should be able to alter both spReference and spSubscriptionId I believe. I don't know if that I clear in the documentation? Do you think otherwise ?

**Comment by teemufrosen** [comment]
Yes, MODIFY should be able to update both spReference and spSubscriptionId, as well as requestedDateTime. Maybe @MaxHellqvist can update the specification with an example?

**Comment by wigerhall** [comment]
> Yes, MODIFY should be able to update both spReference and spSubscriptionId, as well as requestedDateTime. Maybe @MaxHellqvist can update the specification with an example?

This is an important update in the documentation. It has implications of the setup at co. It helps to not have to duplicate data values to make it consistent in responses and reports.

**Comment by DanielMaintrac** [comment]
> Yes, MODIFY should be able to update both spReference and spSubscriptionId, as well as requestedDateTime. Maybe @MaxHellqvist can update the specification with an example?

requestedDateTime is the date and time when the order should be executed.
It can be changed on an order that is in the state "RECEIVED" by a HTTP/PUT or HTTP/PATCH request.

**Comment by teemufrosen** [comment]
> > Yes, MODIFY should be able to update both spReference and spSubscriptionId, as well as requestedDateTime. Maybe @MaxHellqvist can update the specification with an example?
> 
> requestedDateTime is the date and time when the order should be executed.
> It can be changed on an order that is in the state "RECEIVED" by a HTTP/PUT or HTTP/PATCH request.

Correct, thanks for clarifying @DanielMaintrac

**Comment by teemufrosen** [comment]
Clarified the documentation of [orders.md](https://github.com/on-api/on-api/blob/master/2.4.0/spec/orders.md). See below



#### Modify a service
Request
```HTTP
POST /onapi/2.4/orders/ HTTP/1.1
Content-Type: application/json
```
```JSON
{
  "subscriptionId": "35738e19ab534dff9f9becb3a064a7d5",
  "operation": "MODIFY",
  "spReference": "a6cc5da980034948ba654ae6ceda03f4",
  "spSubscriptionId": "d02925f0083b4f64993b365accfbb1ac"
}
```
Response
```HTTP
HTTP/1.1 201 CREATED
Location: /onapi/2.4/orders/f3f26446f6e8407aae876ea8e52d7417
Content-Type: application/json
```
```JSON
{
  "path": "/onapi/2.4/orders/f3f26446f6e8407aae876ea8e52d7417",
  "orderId": "f3f26446f6e8407aae876ea8e52d7417",
  "state": "DONE_SUCCESS"
}
```

  * MODIFY
    * Requires subscriptionId
    * Update a service with "spReference" and/or "spSubscriptionReference"
