### ISSUE TITLE
Time in disconnection date?

### ISSUE THREAD

**Issue by joeseos** [on-api/on-api#28]
looked at the Accesses API and I find it a bit strange that time is not included in the connection & disconnection:

```
    "services": [
      {
        "service": "BB-10-10",
        "connection": "2019-04-19",
        "available": "NO",
        "disconnection": "2021-04-19"
      }
```

When is "2018-12-31"? Sometime between 00:01 and 23:59? Wouldn't it make sense to add time so that a new TL known when it's OK to place an order? I suggest using ISO 8601, I.e. 2018-08-20T14:09:23Z.

**Comment by thoho** [comment]
In this case it's OK to place and order for 2019-01-01... :-D Sorry...
Seriously though, if we add also a timestamp, do we know all systems can adhere to minute precision (or seconds)? Some systems might run connect/disconnect jobs at certain time of day and the specifying a time could lead to unwanted consequences. Since most CO has day as billing resolution it might make sense to have that resolution for orders, ie the "when in the day" is at the CO's discretion and implementation dependent.

**Comment by joeseos** [comment]
> In this case it's OK to place and order for 2019-01-01... :-D Sorry...
> Seriously though, if we add also a timestamp, do we know all systems can adhere to minute precision (or seconds)? Some systems might run connect/disconnect jobs at certain time of day and the specifying a time could lead to unwanted consequences. 

True. But then they could use 00:00:00 and this sort of discussion should be done when implementing and testing between CO & SP. As long as the SP understand if they use time or not, they should be able to build logic for it. Maybe it could help if we add the orderState from Order as well if the CO accepts orders when the termination is in a certain state? For example, if the orderState is in IN_PROGRESS, then I know as an SP to check again and wait to place my order when the orderState is set to DONE_SUCCESS.

> Since most CO has day as billing resolution it might make sense to have that resolution for orders, ie the "when in the day" is at the CO's discretion and implementation dependent.

I agree. "when in the day" should then be shown in 00:00:00.

**Comment by thoho** [comment]
Good suggestion to have the convention that 00:00 could mean "during the day" and another value is "at this time".

**Comment by joeseos** [comment]
> Good suggestion to have the convention that 00:00 could mean "during the day" and another value is "at this time".

I think I formulated myself a bit clumsy, "during the day" should then be 2021-03-03 23:59:59. Then the new SP should know to order the service the next day. But if the CO responds with 2021-03-04 08:59:59 for example, then the SP knows to check again 2021-03-04 09:00:00 to be able to place an order and activate the service as soon as possible.

**Comment by dare-to-recurse** [comment]
Sorry for butting in, I simply have a few thoughts concerning the part mentioned about timing precision

> do we know all systems can adhere to minute precision (or seconds)? Some systems might run connect/disconnect jobs at certain time of day and the specifying a time could lead to unwanted consequences.

Nowadays most systems should _hopefully_ be running on an OS that provides native features (cron or systemd-timers on Linux, Task Scheduler on Windows) for meeting at minimum minute-by-minute precision requirements in job scheduling, so adhering to a requirement for such precision should be fairly easy.

This API is supposed to set the guideline for how such systems should interact with each other, correct?

If that's the case then I think it's okay to do this as a feature change in a future release of the API, as a guideline for systems that then implement the API.

I also feel that providing the opportunity for specifying timestamp removes an uncertainty both for users and during the testing/implementing stage between the SP and CO since it's no longer an implementation dependent behavior, it's specified in the requirements for the API.

If the timestamp part is omitted completely from the input (should this be allowed at all?) then there are two possibilities I would consider logical from a technical point of view:
- the resulting timestamp is selected as 00:00 on the same date
- the resulting timestamp is selected as 23:59 on the same date

From a user point of view, however, it could also be argued that it would make sense if the resulting timestamp is picked during working hours in the local timezone of the system, e.g. 09:00

**Comment by joeseos** [comment]
@dare-to-recurse - Good points and I agree! Suggesting this to be implemented in v. 2.5.

**Comment by teemufrosen** [comment]
I agree with input from @dare-to-recurse! The value in connection, available and disconnection should use the [dateTime dataformat ](https://github.com/on-api/on-api/blob/master/2.4.0/common/dataformats.md#datetime)

**Comment by joeseos** [comment]
Closing this as this has been added to v.2.5.0.
